import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>My Showcase Site</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>Merguez</h1>
      </main>

      <footer></footer>
    </>
  );
}
